import { Bot, Send, ShoppingCart } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { createAiSession, sendAiMessage, type OrderDraft } from './api'

type ChatLine = { role: 'user' | 'assistant'; text: string; draft?: OrderDraft }
export function AssistantDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const { t } = useTranslation('features'); const [sessionId, setSessionId] = useState<string>(); const [text, setText] = useState(''); const [lines, setLines] = useState<ChatLine[]>([]); const [pending, setPending] = useState(false); const endRef = useRef<HTMLDivElement>(null)
  useEffect(() => { if (open && !sessionId) void createAiSession().then((session) => setSessionId(session.id)).catch(() => undefined) }, [open, sessionId])
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [lines])
  async function send() { if (!sessionId || !text.trim() || pending) return; const content = text.trim(); setText(''); setLines((current) => [...current, { role: 'user', text: content }]); setPending(true); try { const result = await sendAiMessage(sessionId, content); if ('text' in result) setLines((current) => [...current, { role: 'assistant', text: result.text }]); else setLines((current) => [...current, { role: 'assistant', text: t('assistant.draftReady'), draft: result }]) } catch (error) { const message = error instanceof Error && error.message ? error.message : t('assistant.error'); setLines((current) => [...current, { role: 'assistant', text: message }]) } finally { setPending(false) } }
  function close(value: boolean) { if (!value) { setSessionId(undefined); setLines([]); setText('') } onOpenChange(value) }
  return <Dialog open={open} onOpenChange={close}><DialogContent className="flex h-[min(720px,calc(100dvh-2rem))] max-w-lg flex-col gap-0 overflow-hidden p-0"><DialogHeader className="border-b px-5 py-4"><DialogTitle className="flex items-center gap-2"><Bot className="h-5 w-5" />{t('assistant.title')}</DialogTitle><DialogDescription>{t('assistant.chatDescription')}</DialogDescription></DialogHeader><div className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-muted/20 p-4">{lines.length === 0 ? <div className="rounded-2xl border bg-card p-4 text-sm text-muted-foreground">{t('assistant.greeting')}</div> : null}{lines.map((line, index) => <div key={index} className={line.role === 'user' ? 'ml-8 rounded-2xl rounded-br-sm bg-primary p-3 text-sm text-primary-foreground' : 'mr-8 rounded-2xl rounded-bl-sm border bg-card p-3 text-sm'}>{line.text}{line.draft ? <Button asChild size="sm" className="mt-3 w-full"><Link to="/orders/new" onClick={() => { sessionStorage.setItem('assistant-order-draft', JSON.stringify(line.draft)); close(false) }}><ShoppingCart className="mr-2 h-4 w-4" />{t('assistant.reviewOrder')}</Link></Button> : null}</div>)}{pending ? <div className="mr-8 rounded-2xl border bg-card p-3 text-sm text-muted-foreground">{t('assistant.working')}</div> : null}<div ref={endRef} /></div><div className="border-t bg-card p-3"><div className="flex items-end gap-2"><Textarea value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send() } }} rows={2} placeholder={t('assistant.placeholder')} className="max-h-32 resize-none" /><Button size="icon" disabled={pending || !text.trim()} onClick={() => void send()} aria-label={t('assistant.send')}><Send className="h-4 w-4" /></Button></div></div></DialogContent></Dialog>
}
